services:
  lovematch:
    image: ${DOCKER_REGISTRY-}lovematch
    build:
      context: .
      dockerfile: LoveMatch/Dockerfile

  lovematch.trivia:
    image: ${DOCKER_REGISTRY-}lovematchtrivia
    build:
      context: .
      dockerfile: LoveMatch.Trivia/Dockerfile

