services:
  lovematch:
    image: ${DOCKER_REGISTRY-}lovematch
    build:
      context: .
      dockerfile: LoveMatch/Dockerfile
    ports:
       - "8080:8080"

  lovematch.trivia:
    image: ${DOCKER_REGISTRY-}lovematchtrivia
    build:
      context: .
      dockerfile: LoveMatch.Trivia/Dockerfile
    ports:
       - "8082:8082"
  lovematch.gamefetcher.api:
    image: ${DOCKER_REGISTRY-}lovematchgamefetcherapi
    build:
      context: .
      dockerfile: LoveMatch.GameFetcher.API/Dockerfile
    ports:
       - "8084:8084"

